# Generated by Django 5.1.6 on 2026-05-29 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scans/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('crop_type', models.CharField(choices=[('tomato', 'Tomato'), ('apple', 'Apple'), ('grape', 'Grape'), ('potato', 'Potato'), ('other', 'Other')], default='other', max_length=50)),
                ('disease_name', models.CharField(max_length=100)),
                ('severity', models.CharField(default='Low', max_length=20)),
                ('health_percentage', models.FloatField(default=100.0)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('recommendation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfectedRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('x_min', models.FloatField()),
                ('y_min', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('scan_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infected_regions', to='api.scanrecord')),
            ],
        ),
    ]
